In [4]:
!dir

 Volume in drive D is New Volume
 Volume Serial Number is 928D-3ED6

 Directory of D:\Assest\Tools_5.3\main

12/14/2022  02:53 PM    <DIR>          .
11/03/2022  11:26 PM    <DIR>          ..
12/14/2022  02:53 PM    <DIR>          .ipynb_checkpoints
12/14/2022  02:47 PM             6,203 ActionFinderModule.py
10/13/2022  03:14 PM             1,602 buildtable.py
10/11/2022  10:18 AM             1,395 build_table_html.py
10/14/2022  10:55 AM            41,259 lib_cluster_maker.py
10/16/2022  07:12 PM                74 main.cmd
11/15/2022  05:31 PM            25,603 main.py
10/16/2022  08:01 PM             4,877 main_cluster_maker.py
10/15/2022  05:22 PM             3,250 scen_gen.py
10/16/2022  08:01 PM             1,850 tools5dot2.py
12/14/2022  02:53 PM                72 Untitled.ipynb
10/11/2022  10:35 AM                 0 __init__.py
12/14/2022  02:47 PM    <DIR>          __pycache__
              11 File(s)         86,185 bytes
               4 Dir(s)  424,122,814,464 bytes free

In [2]:
from collections import defaultdict
import pandas as pd
import json
import webbrowser
import os
import jinja2
import numpy as np
indicator_data = pd.read_csv('../Result/Result from tools5.2/spain_trafo/spain_trafo.csv').rename(
                {
                    'Economic Impact'.upper(): 'EI',
                    'Life Assessment'.upper(): 'LA',
                    'Maintenance Stratgy'.upper(): 'MS',
                    'Economic Impact': 'EI',
                    'Life Assessment': 'LA',
                    'Maintenance Strategy': 'MS'
                }, axis=1)

In [3]:
indicator_data

      name     EI     LA    MS  TOTAL INDICATOR
0   19A649  0.085  0.057  0.00            0.047
1   19A650  0.053  0.049  0.25            0.117
2   19A716  0.070  0.075  0.00            0.048
3   19A754  0.010  0.033  0.00            0.015
4   19P814  0.005  0.015  0.00            0.007
..     ...    ...    ...   ...              ...
87  28PXC6  0.003  0.014  0.00            0.006
88  28PYY2  0.012  0.069  0.00            0.027
89  45ABP7  0.005  0.015  0.00            0.006
90  45PCW7  0.063  0.071  0.00            0.045
91  45PYY8  0.000  0.015  0.00            0.005

[92 rows x 5 columns]

In [4]:
        indicator_categorical = indicator_data.copy()
        columns = indicator_categorical.columns[1:-1]
        def func(value):
            if 1.0 >= value >= 0.75:
                return 'H'
            elif 0.75 > value >= 0.50:
                return 'M'
            elif 0.50 > value >= 0.00:
                return 'L'
            else:
                raise ValueError("Data contains values out of range [1.0, 0.0]")
        try:
            indicator_categorical.loc[:, columns] = indicator_categorical.loc[:, columns].applymap(func)
        except ValueError as e:
            print("DEBUG:")
            print(f"  columns: {columns}")
            print("DATA with ERRORS == True:")
            print(indicator_categorical.loc[:, columns] < 0.0 | indicator_categorical.loc[:, columns] > 1.0)

In [5]:
qtable = pd.read_excel('../files/Q_learning_approach.xlsx', sheet_name='Q_table final')

In [6]:
        data_dict = {}
        columns = indicator_categorical.columns[1:-1]

        data = qtable.iloc[3:, 1:].to_numpy()
        df_columns = qtable.iloc[2, 1:4].to_list() + qtable.iloc[1, 4:].to_list()
        df = pd.DataFrame(data=data, columns=df_columns)
        df = df.convert_dtypes()
        df = df.groupby(columns.to_list()).mean(numeric_only=True)

        values = list(map(tuple, indicator_categorical.loc[:, columns].to_numpy()))
        #print('df')
        #print(df)
        #print('df-info')
        #print(df.info())
        #print('values')
        #print(values)
        decisions = df.loc[values].idxmax(axis=1)
        decisions.name = 'Action'
        decisions = decisions.reset_index()

In [7]:
decisions

   EI LA MS                        Action
0   L  L  L  Keep the current maintenance
1   L  L  L  Keep the current maintenance
2   L  L  L  Keep the current maintenance
3   L  L  L  Keep the current maintenance
4   L  L  L  Keep the current maintenance
.. .. .. ..                           ...
87  L  L  L  Keep the current maintenance
88  L  L  L  Keep the current maintenance
89  L  L  L  Keep the current maintenance
90  L  L  L  Keep the current maintenance
91  L  L  L  Keep the current maintenance

[92 rows x 4 columns]

In [1]:
import pandas as pd
pd.__version__

'1.4.3'

In [7]:
%pip install pandas==1.4.3

Collecting pandas==1.4.3
  Downloading pandas-1.4.3-cp38-cp38-win_amd64.whl (10.6 MB)
Requirement already satisfied: numpy>=1.18.5; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10" in c:\users\glrajora\anaconda3\lib\site-packages (from pandas==1.4.3) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\glrajora\anaconda3\lib\site-packages (from pandas==1.4.3) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\glrajora\anaconda3\lib\site-packages (from pandas==1.4.3) (2020.1)
Requirement already satisfied: six>=1.5 in c:\users\glrajora\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas==1.4.3) (1.16.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.2
    Uninstalling pandas-1.5.2:
      Successfully uninstalled pandas-1.5.2
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\glrajora\\Anaconda3\\Lib\\site-packages\\~-ndas\\_libs\\algos.cp38-win_amd64.pyd'
Consider using the `--user` option or check the permissions.